name: munros
description: A library for filtering and sorting Scottish Munros.
version: 0.0.1
repository: https://github.com/drp33/munros.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.3.0

flutter:
  assets:
    - packages/munros/assets/munrotab_v6.2.csv
